---
dependency:
  name: galaxy
driver:
  name: delegated
  options:
    managed: False
    login_cmd_template: 'ssh {instance}'
    ansible_connection_options:
      connection: ssh
lint:
  name: yamllint
platforms:
  - name: aio1
provisioner:
  name: ansible
  lint:
    name: ansible-lint
  inventory:
    links:
      group_vars: /opt/openstack-ansible/group_vars
      host_vars: /opt/openstack-ansible/host_vars
scenario:
  name: default
verifier:
  name: testinfra
  lint:
    name: flake8
